### ISSUE TITLE
Runner eventually runs out of file descriptors while trying to reconnect

### ISSUE THREAD

**Issue by Kha** [IPDSnelting/velcom#238]
```
Feb 18 19:18:42 i44pc31 java[9978]: 19:18:42.216 [Thread-0] INFO  d.aaaaaaah.velcom.runner.TeleBackend - ws://i44pc22:9666/runner-connector - Connecting
Feb 18 19:18:48 i44pc31 java[9978]: 19:18:48.376 [Thread-0] WARN  d.aaaaaaah.velcom.runner.TeleBackend - ws://i44pc22:9666/runner-connector - Failed to connect, retrying soon
Feb 18 19:18:58 i44pc31 java[9978]: 19:18:58.376 [Thread-0] INFO  d.aaaaaaah.velcom.runner.TeleBackend - ws://i44pc22:9666/runner-connector - Connecting
Feb 18 19:19:04 i44pc31 java[9978]: 19:19:04.536 [Thread-0] WARN  d.aaaaaaah.velcom.runner.TeleBackend - ws://i44pc22:9666/runner-connector - Failed to connect, retrying soon
Feb 18 19:19:14 i44pc31 java[9978]: 19:19:14.537 [Thread-0] INFO  d.aaaaaaah.velcom.runner.TeleBackend - ws://i44pc22:9666/runner-connector - Connecting
Feb 18 19:19:20 i44pc31 java[9978]: 19:19:20.699 [Thread-0] WARN  d.aaaaaaah.velcom.runner.TeleBackend - ws://i44pc22:9666/runner-connector - Failed to connect, retrying soon
Feb 18 19:19:30 i44pc31 java[9978]: 19:19:30.699 [Thread-0] INFO  d.aaaaaaah.velcom.runner.TeleBackend - ws://i44pc22:9666/runner-connector - Connecting
Feb 18 19:19:36 i44pc31 java[9978]: 19:19:36.855 [Thread-0] WARN  d.aaaaaaah.velcom.runner.TeleBackend - ws://i44pc22:9666/runner-connector - Failed to connect, retrying soon
Feb 18 19:19:46 i44pc31 java[9978]: 19:19:46.856 [Thread-0] INFO  d.aaaaaaah.velcom.runner.TeleBackend - ws://i44pc22:9666/runner-connector - Connecting
Feb 18 19:19:53 i44pc31 java[9978]: 19:19:53.016 [Thread-0] WARN  d.aaaaaaah.velcom.runner.TeleBackend - ws://i44pc22:9666/runner-connector - Failed to connect, retrying soon
Feb 18 19:20:03 i44pc31 java[9978]: 19:20:03.016 [Thread-0] INFO  d.aaaaaaah.velcom.runner.TeleBackend - ws://i44pc22:9666/runner-connector - Connecting
Feb 18 19:20:09 i44pc31 java[9978]: 19:20:09.176 [Thread-0] WARN  d.aaaaaaah.velcom.runner.TeleBackend - ws://i44pc22:9666/runner-connector - Failed to connect, retrying soon
Feb 18 19:20:19 i44pc31 java[9978]: 19:20:19.176 [Thread-0] INFO  d.aaaaaaah.velcom.runner.TeleBackend - ws://i44pc22:9666/runner-connector - Connecting
Feb 18 19:20:25 i44pc31 java[9978]: 19:20:25.336 [Thread-0] WARN  d.aaaaaaah.velcom.runner.TeleBackend - ws://i44pc22:9666/runner-connector - Failed to connect, retrying soon
Feb 18 19:20:35 i44pc31 java[9978]: 19:20:35.336 [Thread-0] INFO  d.aaaaaaah.velcom.runner.TeleBackend - ws://i44pc22:9666/runner-connector - Connecting
Feb 18 19:20:41 i44pc31 java[9978]: 19:20:41.501 [Thread-0] WARN  d.aaaaaaah.velcom.runner.TeleBackend - ws://i44pc22:9666/runner-connector - Failed to connect, retrying soon
Feb 18 19:20:51 i44pc31 java[9978]: 19:20:51.501 [Thread-0] INFO  d.aaaaaaah.velcom.runner.TeleBackend - ws://i44pc22:9666/runner-connector - Connecting
Feb 18 19:20:57 i44pc31 java[9978]: 19:20:57.656 [Thread-0] WARN  d.aaaaaaah.velcom.runner.TeleBackend - ws://i44pc22:9666/runner-connector - Failed to connect, retrying soon
Feb 18 19:21:07 i44pc31 java[9978]: 19:21:07.656 [Thread-0] INFO  d.aaaaaaah.velcom.runner.TeleBackend - ws://i44pc22:9666/runner-connector - Connecting
Feb 18 19:21:13 i44pc31 java[9978]: 19:21:13.816 [Thread-0] WARN  d.aaaaaaah.velcom.runner.TeleBackend - ws://i44pc22:9666/runner-connector - Failed to connect, retrying soon
Feb 18 19:21:23 i44pc31 java[9978]: 19:21:23.816 [Thread-0] INFO  d.aaaaaaah.velcom.runner.TeleBackend - ws://i44pc22:9666/runner-connector - Connecting
Feb 18 19:21:29 i44pc31 java[9978]: 19:21:29.976 [Thread-0] WARN  d.aaaaaaah.velcom.runner.TeleBackend - ws://i44pc22:9666/runner-connector - Failed to connect, retrying soon
Feb 18 19:21:39 i44pc31 java[9978]: 19:21:39.976 [Thread-0] INFO  d.aaaaaaah.velcom.runner.TeleBackend - ws://i44pc22:9666/runner-connector - Connecting
Feb 18 19:21:46 i44pc31 java[9978]: 19:21:46.136 [Thread-0] WARN  d.aaaaaaah.velcom.runner.TeleBackend - ws://i44pc22:9666/runner-connector - Failed to connect, retrying soon
Feb 18 19:21:56 i44pc31 java[9978]: 19:21:56.136 [Thread-0] INFO  d.aaaaaaah.velcom.runner.TeleBackend - ws://i44pc22:9666/runner-connector - Connecting
Feb 18 19:21:56 i44pc31 java[9978]: Exception in thread "Thread-0" java.lang.InternalError: java.io.IOException: Zu viele offene Dateien
Feb 18 19:21:56 i44pc31 java[9978]:         at java.net.http/jdk.internal.net.http.HttpClientImpl.<init>(HttpClientImpl.java:311)
Feb 18 19:21:56 i44pc31 java[9978]:         at java.net.http/jdk.internal.net.http.HttpClientImpl.create(HttpClientImpl.java:253)
Feb 18 19:21:56 i44pc31 java[9978]:         at java.net.http/jdk.internal.net.http.HttpClientBuilderImpl.build(HttpClientBuilderImpl.java:135)
Feb 18 19:21:56 i44pc31 java[9978]:         at java.net.http/java.net.http.HttpClient.newHttpClient(HttpClient.java:158)
Feb 18 19:21:56 i44pc31 java[9978]:         at de.aaaaaaah.velcom.runner.Connection.<init>(Connection.java:51)
Feb 18 19:21:56 i44pc31 java[9978]:         at de.aaaaaaah.velcom.runner.TeleBackend.run(TeleBackend.java:92)
Feb 18 19:21:56 i44pc31 java[9978]:         at de.aaaaaaah.velcom.runner.RunnerMain.lambda$realMain$1(RunnerMain.java:62)
Feb 18 19:21:56 i44pc31 java[9978]:         at java.base/java.lang.Thread.run(Thread.java:834)
Feb 18 19:21:56 i44pc31 java[9978]: Caused by: java.io.IOException: Zu viele offene Dateien
Feb 18 19:21:56 i44pc31 java[9978]:         at java.base/sun.nio.ch.IOUtil.makePipe(Native Method)
Feb 18 19:21:56 i44pc31 java[9978]:         at java.base/sun.nio.ch.EPollSelectorImpl.<init>(EPollSelectorImpl.java:83)
Feb 18 19:21:56 i44pc31 java[9978]:         at java.base/sun.nio.ch.EPollSelectorProvider.openSelector(EPollSelectorProvider.java:36)
Feb 18 19:21:56 i44pc31 java[9978]:         at java.base/java.nio.channels.Selector.open(Selector.java:295)
Feb 18 19:21:56 i44pc31 java[9978]:         at java.net.http/jdk.internal.net.http.HttpClientImpl$SelectorManager.<init>(HttpClientImpl.java:699)
Feb 18 19:21:56 i44pc31 java[9978]:         at java.net.http/jdk.internal.net.http.HttpClientImpl.<init>(HttpClientImpl.java:308)
Feb 18 19:21:56 i44pc31 java[9978]:         ... 7 more
```

**Comment by Garmelon** [comment]
Which JDK and JDK version was this running on?

**Comment by Kha** [comment]
Should be OpenJDK 11.0.10+9-0ubuntu

**Comment by Garmelon** [comment]
For some reason, the HttpClient used for the websocket connection relies on GC for cleanup. When testing on my machine with a reconnect delay of 0.1 seconds, it managed to hold up to a few thousand file descriptors (at one point more than 9,000) before GC kicked in and the fds were released again. (Each reconnection attempt is responsible for more than one fd at a time).

If this is the cause of the issue, we could manually kick off GC after a connection closes to make sure the amount of open file descriptors is kept at an acceptable level. Sadly, there seems to be no way to manually force an HttpClient to clean itself up.
